---
title: "자바스크립트 문법 - D - 문자열 주요 메소드 (String methods essential)"

date: "2021-04-06"
categories: 
  - 자바스크립트 문법
tags:
  - 자바스크립트
  - 문법
  - 용어
  - 개념
  - 메소드
  - 문자열
  - String
draft: false
---

:title: Title

//넘버링 각 문서 시작에 써야 개별 문서 프리뷰에서 적용
:sectnums:

//자동 줄바꿈 각 문서 시작에 써야 개별 문서 프리뷰에서 적용
:hardbreaks:

//챕터 이름 Chapter 대신 사용할 이름 설정 (없음 으로 변경)
:chapter-label:

//목차 설정
:toc: left
:toclevels: 5
:toc-title: 목차

= {title}

본 문서의 작성 규칙은 link:../a-작성-규칙_용어와-개념/#_작성_규칙[자바스크립트 문법 작성 규칙] 을 참고하세요.
활용 빈도와 중요도가 높다고 생각되는 항목으로 본문을 구성하였습니다.
나머지 항목은 <<#_기타, 기타>>  챕터에서 확인 가능합니다.

== 문자열 프로퍼티

=== String.length
[source,js]
----
str.length	
//> str의 문자 개수 반환
----

== 문자열 메소드

=== 변환

==== String.prototype.concat()
[source,js]
----
str.concat('s1', 's2', ...'s')	
//> str에 하나 이상의 's'를 합쳐 새로운 str로 반환
----

==== String.prototype.slice()
[source,js]
----
str.slice(start, end)	
//> start부터 end (옵션: 기본 str.length) 전까지 (end 미포함) string을 새로운 str로 반환
----

==== String.prototype.substring()
[source,js]
----
str.substring(start, end)	
//> str을 start 부터 end 전까지 (end 미포함) (옵션 - 기본: str.length) 새로운 str로 반환
----

.*slice, substring 차이점?*
[%collapsible.result]
====
음수인덱스일 경우, slice()는 역방향으로 카운트 / substring() 은 0으로 치환됨
start 가 end 보다 큰 경우, slice()는 빈 문자열 반환 / substring() 은 마치 두 개의 인자를 바꾼 듯 작동
인자가 str.length 보다 큰 경우, substring()은 str.length 로 치환해서 처리 / slice()는 start 가 str.length 큰 경우에는 빈 문자열 반환, end 가 str.length 보다 큰 경우에는 strLength 로 치환

* *동일한 입력값, 동일한 결과값이 나오는 경우*
+
[source,js]
----
// start, end 모두 없는 경우 
"CARROT".slice() // result : "CARROT" 
"CARROT".substring() // result : "CARROT"
----
+
[source,js]
----
// start index 양수 하나인 경우 
"CARROT".slice(3) // result : "ROT" 
"CARROT".substring(3) // result : "ROT"
----
+
[source,js]
----
// start === end 인 경우 
"CARROT".slice(3, 3) // result : "" 
"CARROT".substring(3, 3) // result : ""
----
+
* *start > end*
+
[source,js]
----
"CARROT".slice(4,2) // result : "" 
"CARROT".substring(4,2) // result : "RR" -> 마치 두 개의 인자를 바꾼 듯 작동
----
+
* *음수 인덱스*
+
[source,js]
----
"CARROT".slice(-2) // result : "OT" -> 역방향 인덱스부터 시작 
"CARROT".substring(-2) // result : "CARROT" -> 음수인 경우, 0으로 치환
"CARROT".slice(2, -2) // result : "RR" -> start 는 정방향, end 는 역방향 
"CARROT".substring(2, -2) // result : "CA" -> 음수가 0으로 치환, start > end 이므로 swap
----
+
* *start or end > str.length*
+
[source,js]
----
"CARROT".slice(10, 2) // result : "" 
"CARROT".substring(10, 2) // result : "RROT" -> swap 된 후, 10이 strLength로 치환
----
+
출처: https://interacting.tistory.com/144
====

	
	
	
==== String.prototype.split()
[source,js]
----
str.split('s', n)	
// str을 's' 구분자 (옵션: 기본 구분자 없음) 로 n 개 (옵션: 기본 str.length) 까지 분할해 새로운 arr로 반환
----

* *관련 메소드*
+
[source,js]
----
arr.join('s')
// arr의 모든 item을 사이에 's' 구분자를 넣어 더해 새로운 str로 반환, item이 undefined 또는 null이면 빈 str로 반환
----

==== String.prototype.toLowerCase()
[source,js]
----
str.toLowerCase()	
// str을 소문자로 변환하여 새로운 str로 반환
----

==== String.prototype.toUpperCase()
[source,js]
----
str.toUpperCase()	
// str을 대문자로 변환하여 새로운 str로 반환
----

==== String.prototype.padStart()
[source,js]
----
str.padStart(n, 's')	
str의 길이가 n이 될때까지 's'를 좌측부터 채워 새로운 str로 반환
----

* *예시*
+
[source,js]
----
const str = 'abcd'
str.padStart(10, '.')
//> "......abcd"
----

==== String.prototype.padEnd()
[source,js]
----
str.padEnd(n, 's')	
str의 길이가 n이 될때까지 's'를 우측부터 채워 새로운 str을 반환합니다.
----
* *예시*
+
[source,js]
----
const str = 'abcd'
str.padEnd(10, '.')
//> "abcd......"
----

==== String.prototype.repeat()
[source,js]
----
str.repeat(n);	
//str을 n번 반복해 붙인 새로운 str 반환
----

==== String.prototype.replace() - string // 보강 필요
[source,js]
----
str.replace('r1/s1', 's2')	
// str의 r1/s1과 일치하는 첫 부분을 s2로 교체한 새로운 str 반환
----

* *예시*
+
[source,js]
----
const str = 'aabbcc'
str.replace('b', 'k')
//> "aakbcc"
----

[#특수-페턴]
* *특수 페턴* 
** $$: "$" 기호 삽입
** $&: 매치된 문자열을 삽입합니다.
** $`: 매치된 문자열 앞쪽까지의 문자열을 삽입합니다.
** $': 매치된 문자열의 문자열을 삽입합니다.
** $n: n이 1이상 99이하의 정수라면, 첫번째 매개변수로 넘겨진 RegExp객체에서 소괄호로 묶인 n번째의 부분 표현식으로 매치된 문자열을 삽입합니다.
	
==== String.prototype.replace() - func // 보강 필요
[source,js]
----
str.replace('r/s1', p => p + 1)	
// str의 r1/s1과 일치할 경우 연산 함수 호출, 연산 결과를 문자열로 반환 
----

* <<특수-페턴, 특수 페턴>>은 반환값에 적용되지 않음, 정규표현식의 플래그로 글로벌(g)이 오는 경우, 일치될 때마다 계속 함수 호출

[#replace_함수_P]
* *함수 p*
** match: 일치 string (<<특수-페턴, 특수 페턴>> $& 표현식으로 매치된 경우와 동일)
** p1, p2, ...p: <<특수-페턴, 특수 페턴>> $n 표현식과 동일 ($1은 p1, $2는 p2) (정규표현식 /(\a+)(\b+)/ 이 주어진다면 p1은 \a+, p2는 \b+와 매치)
** offset: 일치 string의 index (예를 들어, 조사될 전체 문자열이 abcd이고, 매치된 문자열이 bc면 이 매개변수의 값은 1이 됩니다.)
** string: 조사된 전체 문자열 (replace를 호출한 str)
	
==== String.prototype.replaceAll()
[source,js]
----
str.replaceAll('r/s1', 's2')	
// str의 r1/s1과 일치하는 모든 부분을 s2로 교체한 새로운 str 반환
----

* *예시*
+
[source,js]
----
const str = 'aabbcc'
str.replace('b', 'k')
//> "aakkcc"
----
<<특수-페턴, 특수 페턴>> 적용
	
==== String.prototype.replaceAll()
[source,js]
----
str.replaceAll('r/a1', p => p + 1)	
// str의 string이 r1/a1과 일치할 경우 연산 함수 호출, 연산 결과를 문자열로 반환 
----
* *예시*
+
[source,js]
----
const str = 'aabbcc'
str.replace('b', 'k')
//> "aakkcc"
----
<<특수-페턴, 특수 페턴>>은 반환값에 적용되지 않음
<<replace_함수_P, 함수 P>> 적용
	
==== String.prototype.toString()
[source,js]
----
H.toString()	
// H를 str로 변환하여 반환
----


=== 검색 & 확인

==== String.prototype.includes()
[source,js]
----
str.includes('s', start)	
// str의 's'의 존재 여부를 start (옵션: 기본 0) 부터 차례로 확인, true/false 반환
----
	
==== String.prototype.indexOf()
[source,js]
----
str.indexOf('s', start)	
// str의 's'의 존재 여부를 start (옵션: 기본 0) 부터 차례로 확인, index를 반환, 없으면 -1 반환
----

==== String.prototype.lastIndexOf()
[source,js]
----
str.lastIndexOf('s', end)	
// indexOf() 와 달리 end부터 (옵션 - 기본: 1/0) 역순으로 검색
----

==== String.prototype.startsWith()
[source,js]
----
str.startsWith('s', n)	
// str의 시작과 's'의 일치 여부를 n 번째 index (옵션 - 기본: 0) 부터 확인, true/false 반환
----

==== String.prototype.search()
[source,js]
----
str.search(r/)	
// str에서 r/과 일치하는 항목 검색, 일치하는 첫번째 index 반환, 없으면 -1 반환
----

==== String.prototype.endsWith()
[source,js]
----
str.endsWith('s'))	
//str의 마지막과 's' 와의 일치 여부를 true/false 로 반환
----

* *예시*
+
[source,js]
----
const str = 'abcdef'
str.endsWith('def') // true
str.endsWith('bc') // false
----

==== String.prototype.at()
[source,js]
----
str.at(index)	
// 실험 기능
// str의 index에 해당하는 글자 반환
// charAt() 과 차이점: index 음수 가능
----

	
==== String.prototype.charAt()
[source,js]
----
str.at(index)	
// str의 index (옵션 - 기본: 0) 에 해당하는 글자 반환
// at() 과 차이점: index 음수 불가
----


=== 기타

==== String.prototype.trim()
[source,js]
----
str.trim()	
// str 양 끝의 모든 공백문자(space, tab, NBSP 등)와 모든 개행문자(LF, CR 등)를 제거, 새로운 str 반환	
----
	
	
==== String.prototype.trimEnd() /	String.prototype.trimRight()
[source,js]
----
str.trimEnd()	
// str 끝의 모든 공백문자(space, tab, NBSP 등)와 모든 개행문자(LF, CR 등)를 제거, 새로운 str 반환	
----
	
	
==== String.prototype.trimStart() / String.prototype.trimLeft()
[source,js]
----
str.trimStart	
// str 시작의 모든 공백문자(space, tab, NBSP 등)와 모든 개행문자(LF, CR 등)를 제거, 새로운 str 반환	
----

==== String.prototype.charCodeAt()
[source,js]
----
str.charCodeAt(index)	
// str의 index (옵션 - 기본: 0) 에 해당하는 글자를 UTF-16 코드로 반환	
----

==== String.fromCharCode()
[source,js]
----
String.fromCharCode(n)	
// n (UTF-16 코드) 을 str로 반환	
----
* *예시*
+
[source,js]
----	
String.fromCharCode(189, 43, 190, 61)	
//> "½+¾="	
----

==== String.prototype.codePointAt()
[source,js]
----
str.codePointAt(index)	
// str의 index (옵션 - 기본: 0) 에 해당하는 글자의 코드 포인트 값을 반환	
//charCodeAt() 과 차이점: 일반 문자의 경우 반환값이 동일하지만, 단일 UTF-16 코드로 표현할 수 없는 문자 (ex. 이모지) 는 다름	
----
http://www.devdic.com/javascript/refer/native/method:1371/codePointAt()	

==== String.fromCodePoint()
[source,js]
----
String.fromCodePoint(n)	
// n (코드 포인트) 를 str로 반환	
----

* *예시*
+
[source,js]
----	
String.fromCodePoint(9731, 9733, 9842, 0x2F804)	
//> "☃★♲你"	
----

==== String.prototype.localeCompare()
[source,js]
----
str.localCompare('s')	
//str과 's'의 정렬 순서에 따른 숫자 반환 (str - 's': -1, str = 's': 0, 's' - str: 1)	
----

==== String.prototype.normalize()
[source,js]
----
str.normalize(form)	
// str을 form (유니코드 정규화 방식, Unicode Normalization Form)에 따라 정규화된 형태로 반환, str이 문자열이 아닐 경우에는 우선 문자열로 변환 후 정규화	
----

* *form*	
** NFC — 정규형 정준 결합(Normalization Form Canonical Composition).	
** NFD — 정규형 정준 분해(Normalization Form Canonical Decomposition).	
** NFKC — 정규형 호환성 결합(Normalization Form Compatibility Composition).	
** NFKD — 정규형 호환성 분해(Normalization Form Compatibility Decomposition)	
	
==== String.raw
[source,js]
----
String.raw`{a}`	
// 템플릿의 표현식의 결과를 그대로 표현하여 출력합니다. 특수문자와 유니코드는 문자열로 인식합니다.	
----

* *예시*
+
[source,js]
----	
String.raw`Hi\n${2+3}!`	
//> "Hi\n5!"	
----
https://mollangk.tistory.com/32	
	
==== String.raw()
[source,js]
----
String.raw({raw:str}, a1, a2, …a)	
// str과 하나 이상의 a를 차례로 1개씩 합친 새로운 str 반환	
----

* *예시*
+
[source,js]
----	
const one = 1	
String.raw({raw:'ABDCEF'}, one, 2)	
//> "A1B2DCEF"	
----
https://mollangk.tistory.com/32	
	
==== String.prototype.toLocaleLowerCase()
[source,js]
----
H.toLocaleLowerCase()	
// 숫자 및 숫자가 포함된 대상을 지역에 따른 표현을 적용한 소문자 str로 반환 (원본 H 유지)	
----
	
==== String.prototype.toLocaleUpperCase()
[source,js]
----
H.toLocaleUpperCase()	
// 숫자 및 숫자가 포함된 대상을 지역에 따른 표현을 적용한 대문자 str로 반환 (원본 H 유지)	
----

==== String.prototype.match()
[source,js]
----
str.match(regexp)	
// 정규표현식
// str이 regexp와 일치하면, 일치하는 전체 str을 첫번째 item으로 하고 이후 괄호 한 캡처 결과를 포함하는 arr 반환, 일치 항목이 없으면 null 반환
// 정규식에 g 플래그가 포함되어있지 않으면, str.match() 는 RegExp.exec()와 같은 결과를 반환
// 정규식에 g 플래그가 포함되어 있으면, 일치는 객체가 아닌 일치하는 하위 문자열을 포함하는 Array를 반환합니다. 캡처된 그룹은 반환되지 않습니다. 일치하는 것이 없으면 null이 반환됩니다.
----
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/String/match

* *관련 메소드*
** RegExp.test(): 문자열이 정규표현식과 일치하는지 여부를 알아야할 때, 
** RegExp.exec(): 일치하는 것 중 제일 첫번째 것만 알고싶을 때, 캡처 그룹을 알고 싶고 전역 플래그가 셋팅되어 있을 때

==== String.prototype.matchAll()
[source,js]
----
str.matchAll(regexp)	
// 정규표현식	
// str이 regexp와 일치하면, 일치하는 전체 str을 첫번째 item으로 하고 이후 괄호 안 캡처 결과를 포함하는 arr 반환, 일치 항목이 없으면 null 반환	
----

==== String.prototype.valueOf()
[source,js]
----
str.valueOf()
// str의 원시값 반환	
----

=== 사용 금지 (웹 표준 아님)

==== String.prototype.anchor()	
	
==== String.prototype.big()	
	
==== String.prototype.blink()	
	
==== String.prototype.bold()	
	
==== String.prototype.fixed()	
	
==== String.prototype.fontcolor()	
	
==== String.prototype.fontsize()	
	
==== String.prototype.italics()	
	
==== String.prototype.link()	
	
==== String.prototype.small()	
	
==== String.prototype.strike()	
	
==== String.prototype.sub()	
	
==== String.prototype.substr()	
	
==== String.prototype.sup()	
	
==== String.prototype.toSource()	








