---
title: "자바스크립트 문법 - E - 맵 주요 메소드 (Map methods essential)"

date: "2021-04-08"
categories: 
  - 자바스크립트 문법
tags:
  - 자바스크립트
  - 문법
  - 용어
  - 개념
  - 메소드
  - 맵
  - Map
draft: false
---

:title: Title

//넘버링 각 문서 시작에 써야 개별 문서 프리뷰에서 적용
:sectnums:

//자동 줄바꿈 각 문서 시작에 써야 개별 문서 프리뷰에서 적용
:hardbreaks:

//챕터 이름 Chapter 대신 사용할 이름 설정 (없음 으로 변경)
:chapter-label:

//목차 설정
:toc: left
:toclevels: 5
:toc-title: 목차

= {title}

본 문서의 작성 규칙은 link:../a-작성-규칙_용어와-개념/#_작성_규칙[자바스크립트 문법 작성 규칙] 을 참고하세요.
활용 빈도와 중요도가 높다고 생각되는 항목으로 본문을 구성하였습니다.
나머지 항목은 <<#_기타, 기타>>  챕터에서 확인 가능합니다.


== Map

=== 특징
* key, value 쌍을 저장하며 삽입 순서도 기억하는 컬렉션

====
* 객체 (Object) 대신 맵 (Map) 을 사용해야 하는 경우
. 동적인 대상을 컬렉션화 할 경우
** Object는 경로를 알고 있는 정적인 정보에 적합. 갱신, 반복, 대체 정렬해야 할 정보에는 적절하지 않음
** 탐색 성능에서 Map이 더 뛰어남
. 숫자 또는 Object를 key로 사용해야 하는 경우
** Object의 키는 반드시 String 또는 Symbol이어야 함
** 이외의 값을 key로 사용해야 할 경우에 Map 사용
. 컬렉션을 순회해야 할 경우
** Object를 순회하려면 다른 형태로 변환 (복잡) 하거나, for in 문을 사용 (key 값 외에는 접근 불가) 해야하고 모든 경우에 순서 보장되지 않음
** 순회를 용이하게 하려면 Map 사용
====

====
* 맵 (Map) 과 객체 (Object) 의 차이점
. 기본 key
** Map: 제공한 키 외에는 어떤 키도 가지지 않음
** Object: 프로토타입을 가지므로 기본 키 존재 가능, 제공한 키와 충돌 가능
. 가능 key
** Map: 숫자, 객체 등을 포함한 모든 값 가능
** Object: String 또는 Symbol
. key 순서
** Map: 정렬됨. 삽입 순서에 따라 순회 
** Object: 키는 정렬되지 않음. (ECMEScript 2015 준수 엔진에서 문자열 키만 가진 객체는 정렬됨)
. 크기 
** Map: size 속성으로 바로 확인 가능
** Object: 구조 변경등의 부수 작업 필요
. 순회
** Map: 바로 순회 가능 (for of, forEach 로 접근 가능, [key,value] of map 으로 key, value 따로 접근 가능) 
** Object: 순회하려면 먼저 모든 키를 알아낸 후, 그 키의 배열을 순회해야 함 (for in 순회 가능하나 느리고 순서 보장 안함)
. 성능
** Map: 잦은 src 추가와 제거에서 더 좋은 성능
** Object: src 추가와 제거를 위한 최적화 없음
====

=== 기본 문법

==== 선언
[source,js]
----
const map = new Map()
----

==== src 추가
[source,js]
----
map.set(key, value)
----

==== value 호출
[source,js]
----
map.get(key)
----




== Map 프로퍼티

=== Map.prototype.size
[source,js]
----
map.size		
// map의 src 갯수 반환	
// map.length 는 값이 0인 속성	
----



== Map 메소드

=== 직접 수정

==== Map.prototype.clear()
[source,js]
----
map.clear()		
// map의 모든 src를 제거 (원본 map 변경), undefined 반환	
----

==== Map.prototype.delete()
[source,js]
----		
map.delete(key)		
// map의 key 관련 src를 제거, 제거 여부 true/false 반환	
----




=== 확인 & 검색

==== Map.prototype.get()
[source,js]
----		
map.get(key)		
// map의 key에 해당하는 value 반환, 없으면 undefined 반환	
----

==== Map.prototype.set()
[source,js]
----
map.set(k1, v1).set(k2, v2).set(...k, ...v)		
// map에 하나 이상의 src 추가 및 갱신	
----

==== Map.prototype.has()
[source,js]
----
map.has(key)		
// key의 존재 여부 확인, true/false 반환	
----




=== 관련 요소 반환

==== Map.prototype.forEach()
[source,js]
----
map.forEach((value, key) => value + 1)		
// map의 src에 차례로 연산 함수 적용, 중간 탈출 불가, undefine 반환	
// 연산 함수의 value, key 순서에 주의	
// forEach 의 경우, 인자 순서가 이상한데(key, value 순서가 반대) Array.prototype.forEach() 구문과 통일성을 유지하기 위함(value, index, array 순서인 것)
----

==== Map.prototype.keys()
[source,js]
----
map.keys()		
// map의 key를 차례로 제공하는 새로운 iterator 반환	
----

==== Map.prototype.values()
[source,js]
----
map.values()		
// map의 value를 차례로 제공하는 새로운 iterator 반환	
----

==== Map.prototype.entries()
[source,js]
----
map.entries()		
// map의 src 배열을 차례로 제공하는 iterator 반환	
----




=== 기타

.*눌러서 확인*
[%collapsible.result]
====
* *get Map[@@species]*
+
[source,js]
----
Map[Symbol.species]		
// 값이 0인 속성, src 수는 Map.prototype.size로 확인 가능	
----

* *Map.prototype[@@toStringTag]*
+
[source,js]
----
Object.prototype.toString.call(new Map())		
// 파생 객체를 생성하는데 사용하는 생성자 함수
----

* *Map.prototype[@@iterator]()*
+
[source,js]
----
map[Symbol.iterator]()		
// map의 src를 차례로 제공하는 iterator 반환	
// entries() 와 같음	
----
====

== 활용

=== obj ↔ map 변환
[source,js]
----
/// obj -> map 변환 (Object.entries)
let obj = {name: "John", age: 30};
let map = new Map(Object.entries(obj));
map.get('name')
//> John
----
[source,js]
----
/// map -> obj 변환 (Object.fromEntries)	
let map = new Map();
map.set('a', 1);
map.set('b', 2);
let obj = Object.fromEntries(map.entries());
//> obj = { a: 1, b: 2 }	
----

=== arr ↔ map 변환
[source,js]
----
/// arr -> map 변환
const map = new Map ([[k1, v1],[k2, v2],[...k, ...v]])
----
[source,js]
----
/// map ->> arr 변환 (펼침 연산자)	
[...map]
//> [[k1, v1], [k2, v2], [...k, ...v]]
----












