---
title: "자바스크립트 문법 - B - 배열 메소드 (Array methods)"

date: "2021-04-04"
categories: 
  - 자바스크립트 문법
tags:
  - 자바스크립트
  - 문법
  - 용어
  - 개념
  - 배열
  - 메소드
draft: false
---

:title: 자바스크립트 문법 - B - 배열 메소드 (Array method)

//넘버링 각 문서 시작에 써야 개별 문서 프리뷰에서 적용
:sectnums:

//자동 줄바꿈 각 문서 시작에 써야 개별 문서 프리뷰에서 적용
:hardbreaks:

//챕터 이름 Chapter 대신 사용할 이름 설정 (없음 으로 변경)
:chapter-label:

//목차 설정
:toc: left
:toclevels: 5
:toc-title: 목차

= {title}

본 문서의 작성 규칙은 link:../a-작성-규칙_용어와-개념/[자바스크립트 문법 작성 규칙, title = 작성 규칙] 을 참고하세요.

== 배열 프로퍼티

=== Array.prototype.length
[source,js]
----
arr.length 
// arr의 item 갯수 반환
----

== 배열 메소드


=== 직접 수정
원본 배열을 직접 수정하여 변경합니다.

==== Array.prototype.shift()
[source,js]
----
arr.shift()
// arr의 첫 번째 요소를 제거 (원본 arr 변경), 제거된 요소를 반환
----

==== Array.prototype.unshift()
[source,js]
----
arr.unshift(a) 
// a를 arr의 첫 item으로 추가 (원본 arr 변경), 새로운 길이를 반환
----

==== Array.prototype.pop()
[source,js]
----
arr.pop() 
// arr의 마지막 item을 제거 (원본 arr 변경), 제거한 item을 반환, 빈 arr은 undefined 반환
----

==== Array.prototype.push()
[source,js]
----
arr.push(a1, a2, ...a)
// arr의 끝에 하나 이상의 a 추가 (원본 arr 변경), arr의 새로운 길이를 반환. (원본 변경)
----

.*눌러서 추가 활용 방법 확인*
[%collapsible.result]
====
[source,js]
----
/// 두 배열 합치기, concat()은 원본 유지
Array.prototype.push.apply(arr, arr1)
----
====

==== Array.prototype.splice()
[source,js]
----
arr.splice(start, n, a1, a2, ...a) 
// start 부터 n개 (옵션: 기본 end 까지) item 삭제 후 그 자리에 하나 이상의 a (옵션: 기본 없음) 추가 (원본 arr 변경), 제거한 item들로 구성된 arr 반환
----

==== Array.prototype.fill()
[source,js]
----
arr.fill(a, start, end) 
// start (옵션: 기본 0) 에서 end (옵션: 기본 arr.length) 까지 item을 a로 채움 (원본 arr 변경), 변경된 arr 반환
----

==== Array.prototype.copyWithin()
[source,js]
----
arr.copyWithin(target, start, end) 
// arr의 start (옵션: 기본 0) 에서 end (옵션: 기본 arr.length) 까지 item을 복사하여 target 부터 덮어씌움 (원본 arr 변경), 변경된 arr 반환
----


==== Array.prototype.sort()
[source,js]
----
arr.sort((a , b) => a - b ) 
// 정렬 함수 기준으로 정렬 (원본 arr 변경), 변경된 arr 반환
----
[source,js]
----
/// 정렬 함수
(a, b) => a - b
// a - b 오름차순 : 1, 2, 3, a, b, c
// b - a 내림차순 : c, b, a, 3, 2, 1
// (옵션: 기본 문자열 기준 유니코드) 
----

==== Array.prototype.reverse()
[source,js]
----
arr.reverse() 
// arr의 순서를 반전 (원본 arr 변경), 변경된 arr 반환
----

==== Array.prototype.flat() 
[source,js]
----
arr.flat(n)
//고차 arr을 n (옵션: 기본 1) 만큼 차수 낮춤 (원본 arr 변경), 변경된 arr 반환
----
.눌러서 예시 확인
[%collapsible.result]
====
[source,js]
----
/// 예시
arr.flat(1) // [1,[2]] -> [1,2] / [1,[2,[3]]] -> [1,2,[3]]
arr.flat(2) // [1,[2,[3]]] -> [1,2,3]
----
====
.눌러서 활용법 확인
[%collapsible.result]
====
[source,js]
----
/// 배열 구멍 제거
const arr = [1, 2, , 4, 5]
arr.flat()
//> [1, 2, 4, 5]
----
====

=== 변환
원본 배열은 유지한채 내부 요소를 변환하여 반환합니다.

==== Array.prototype.concat()
[source,js]
----
arr.concat(a1, a2, ...a) 
// arr에 하나 이상의 a (arr, item) 를 합쳐 새로운 arr 반환
----

==== Array.prototype.join()
[source,js]
----
arr.join('a')
// arr의 모든 item을 사이에 'a' 구분자를 넣어 더해 새로운 str로 반환, item이 undefined 또는 null이면 빈 str로 반환
----
[source,js]
----
/// 문자열 분할
str.split('a', n)
// str을 'a' 구분자 (옵션: 기본 구분자 없음) 로 n 개 (옵션: 기본 str.length) 까지 분할해 새로운 arr로 반환
----

==== Array.prototype.slice()
[source,js]
----
arr.slice(start, end) 
// start부터 end (옵션: 기본 arr.length) 전까지 (end 미포함) item을 새로운 arr로 반환
----

==== Array.prototype.toString()
[source,js]
----
arr.toString() 
// item들을 쉼표를 구분자로 합쳐 새로운 str로 반환
----

.*눌러서 예시 확인*
[%collapsible.result]
====
[source,js]
----
const arr = [1,2,3,4,5]
console.log(arr.toString())
//> 1,2,3,4,5
----
====

=== 검색 & 확인
배열의 item 또는 배열 자체를 검색하고 확인합니다.

==== Array.prototype.every() 
[source,js]
----
arr.every(p => p < 10)
// 모든 item이 판별 함수를 만족하면 true, 불만족 item 발견 시 false, 빈 배열은 true 반환
----

==== Array.prototype.some()
[source,js]
----
arr.some(p => p > 10) 
// 판별 함수를 만족하는 item 발견 시 true, 모두 불만족하면 false 반환, 빈 배열은 false 반환
----

==== Array.prototype.filter()
[source,js]
----
arr.filter(p => p < 10) 
// 판별 함수를 만족하는 item을 모아 새로운 arr 반환
----

==== Array.prototype.find()
[source,js]
----
arr.find(p => p < 10) 
// 판별 함수를 만족하는 첫번째 item을 반환, 없으면 undefined 반환
----

==== Array.prototype.findIndex()
[source,js]
----
arr.find(p => p < 10) 
//판별 함수를 만족하는 첫번째 item의 index를 반환, 없으면 -1 반환
----

==== Array.prototype.includes()
[source,js]
----
arr.includes(a) 
// arr의 item 중 a의 존재 여부 확인, 있으면 true 반환, 없으면 false 반환
----

==== Array.prototype.indexOf()
[source,js]
----
arr.indexOf(a, n) 
// arr의 item 중 a의 존재 여부 확인, n 번째 (옵션: 기본 1) index를 반환, 없으면 -1 반환
----

.*눌러서 추가 활용 방법 확인*
[%collapsible.result]
====
[source,js]
----
/// 특정 item의 모든 index 찾기
  var indices = [];
  var array = ['a', 'b', 'a', 'c', 'a', 'd'];
  var element = 'a';
  var idx = array.indexOf(element);
  while (idx != -1) {
    indices.push(idx);
    idx = array.indexOf(element, idx + 1);
  }
  console.log(indices);
//> [0, 2, 4]
----
[source,js]
----
/// arr내 특정 item 존재 여부 확인 후 없으면 추가
  function updateVegetablesCollection (veggies, veggie) {
    if (veggies.indexOf(veggie) === -1) {
        veggies.push(veggie);
        console.log('새로운 veggies 컬렉션 : ' + veggies);
    } else if (veggies.indexOf(veggie) > -1) {
        console.log(veggie + ' 은 이미 veggies 컬렉션에 존재합니다.');
    }
  }
  var veggies = ['potato', 'tomato', 'chillies', 'green-pepper'];
  updateVegetablesCollection(veggies, 'spinach');
//> 새로운 veggies 컬렉션 : potato, tomato, chillies, green-pepper, spinach
  updateVegetablesCollection(veggies, 'spinach');
//> spinach 은 이미 veggies 컬렉션에 존재합니다.
----
====

==== Array.prototype.lastIndexOf()
[source,js]
----
arr.lastIndexOf() 
// indexOf() 와 달리 마지막 index 반환, 없으면 -1 반환
----

==== Array.isArray()
[source,js]
----
Array.isArray(a) 
// a가 배열인지 판별, true/false 반환
----

=== 연산
배열 내 item들에 대한 연산을 수행합니다.

==== Array.prototype.forEach()
[source,js]
----
arr.forEach(p => p + 1) 
// start 부터 end 까지 연산 함수 적용, 중간 탈출 불가, undefine 반환
----

==== Array.prototype.map()
[source,js]
----
arr.map(x => x + 1) 
// arr의 item에 연산 함수를 차례로 적용, 새로운 arr 반환 
----

.*눌러서 주의사항 확인*
[%collapsible.result]
====
[source,js]
----
/// 두개 이상의 p를 받는 연산 함수를 적용 시 기대와 다른 결과값이 나오므로 주의
['1', '2', '3'].map(parseInt) 
----
====

==== Array.prototype.flatMap() 
[source,js]
----
arr.flatMap(p => p + 1)
// arr.map(p => p + 1).flat(1)
----

.*눌러서 주의사항 확인*
[%collapsible.result]
====
[source,js]
----
/// flat().map() 이 아님
console.log([1, 2, [3, 3]].flat().map(x => x + 1))
///> [2, 3, 4, 4]

console.log([1, 2, [3, 3]].map(x => x + 1).flat())
///> [2, 3, "3,31"]
----
====

==== Array.prototype.reduce()
[source,js]
----
arr.reduce((acc, cur) => acc + cur)
arr.reduce((acc, cur, inx, src) => acc + cur, int)
// arr의 각 item을 차례로 cur에 대입하고 리듀서 함수를 적용, 결과를 acc에 누적하여 반환
----
[source,js]
----
/// 리듀서 (reducer) 함수: int (옵션: 기본 0) 를 초기값으로 시작, arr의 각 item이 차례로 cur에 대입되어 연산 함수를 적용한 뒤 acc에 누적 저장하여 반환
// acc: accumulator, cur: currentValue, idx: currentIndex, src: sourceArray, int: initialValue
----
.*눌러서 주의사항 확인*
[%collapsible.result]
====
각 항목이 모두 리듀서 함수를 거치게 하려면 초기값 (init: initialValue) 을 주어야 한다.
초기값이 제공되지 않았다면,
. 배열의 첫번째 요소 (0번 인덱스) 를 accumulator에 누적한 후 1번 인덱스부터 리듀서 함수를 거친다. (0번 인덱스 항목은 리듀서 함수를 거치지 않음)
. 배열의 요소 값이 1개인데 초기값도 제공하지 않은 경우 or 초기값은 있지만 배열이 빈 배열인 경우에는 그 단독 값을 리듀서를 거치지 않고 바로 반환
. 배열이 비었는데 초기값도 없는 상태에서 reduce() 를 호출하면 TypeError 오류가 발생
====
.*눌러서 추가 예시 확인*
[%collapsible.result]
====
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce
====

==== Array.prototype.reduceRight()
[source,js]
----
arr.reduceRight((acc, cur) => acc + cur)
arr.reduceRight((acc, cur, inx, src) => acc + cur, int)
// reduce() 와 같으나 item을 역순으로 cur에 대입
----

==== Array.from()
[source,js]
----
Array.from(H, p => p + 1) 
// H ('a', arr, array-like, iterable, (p1, p2, ...p)) 를 각 item에 연산 함수 (옵션: 기본 p => p) 적용, 새로운 arr 반환
----



=== 관련 요소 반환
배열 연관 요소를 반환합니다.

==== Array.prototype.keys()
[source,js]
----
arr.keys()
// arr의 index를 차례로 제공하는 새로운 iterator 반환
----

==== Array.prototype.values()
[source,js]
----
arr.values() 
// arr의 item을 차례로 제공하는 새로운 iterator 반환
----

==== Array.prototype.entries() 
[source,js]
----
arr.entries()
// [index, item] 을 차례로 제공하는 새로운 iterator 반환 
----


=== 기타

==== Array.of()
[source,js]
----
Array.of(a1, a2, ...a)
// [a1, a2, ...a] 반환
----

==== Array.prototype.toLocaleString()
[source,js]
----
H.toLocaleString() 
// 숫자 및 숫자가 포함된 대상을 지역에 따른 표현을 적용한 문자열로 반환 (원본 H 유지)
----

.*눌러서 예시 확인*
[%collapsible.result]
====
[source,js]
----
const num = 12341.23
console.log(num.toLocaleString("ko-KR", { style: 'currency', currency: 'KRW' }));
//> ₩12,341
----
====

==== Array.prototype.toSource() 
[source,js]
----
// <현재 지원 안함> 배열의 소스 코드 문자열을 반환
----











