---
title: "자바스크립트 문법 - A - 작성 규칙, 용어와 개념 (Style, Terms and Con"
categories: 
  - 자바스크립트 문법
tags:
  - 자바스크립트
  - 문법
  - 작성 규칙
  - 용어
  - 개념
date: "2021-04-03"
draft: false
---

:title: 자바스크립트 문법 - A - 작성 규칙, 용어와 개념

//넘버링 각 문서 시작에 써야 개별 문서 프리뷰에서 적용
:sectnums:

//자동 줄바꿈 각 문서 시작에 써야 개별 문서 프리뷰에서 적용
:hardbreaks:

//챕터 이름 Chapter 대신 사용할 이름 설정 (없음 으로 변경)
:chapter-label:

//목차 설정
:toc: left
:toclevels: 5
:toc-title: 목차

= {title}

정식 표기법을 문자화, 단순화시켜 실제 사용되는 형태로 표현했습니다. 그 과정에서 다소 생략, 또는 비약이 있을 수 있습니다.
반환값, 기존 대상의 변경 여부, 항목의 생략 가능 여부와 생략했을때 기본값을 명확히 하는데 중점을 뒀습니다.
학습 과정중, 정리를 위해 작성하여 오류가 있을 수 있습니다. 이에 대해 제 스스로 알게되거나, 관련 내용을 전달해 주신다면 업데이트 하도록 하겠습니다.


== 작성 규칙

// 추후 업데이트 예정

// 정식 표기법 예시

// 본 문서 표기 예시

* *배열 예시*
** 정식 표기법

** 본문 표기법


* *문자열 예시*
* *객체 예시*
* *Map 예시*
* *Set 예시*


=== 기존 대상

=== 항목

=== 항목별 설명 순서
기능 설명 -> (원본 변경/유지 여부) -> 반환값

=== 기존 대상의 변경 여부 표시
* 기존 대상 변경: 변경된 대상 반환 (원본 변경) - 기능 설명에 표시
* 기존 대상 유지: 새로운 대상 반환 (원본 유지) - 기능 설명에 미표시

=== 생략 가능한 항목의 생략 시 기본값

[source]
----
(옵션: 기본 0)
----

=== 대상 표기

==== 공통 (숫자, 불리언, 지정 문자열, 지정 값, 지정 인덱스)
[source,js]
----
n // 0 포함 자연수
-n // 음의 정수
1/0 // 무한대 (Infinity) 
true/false // 불리언
'a' // 지정 문자열
a, b, c, ... // 지정 값
target, // 지정 인덱스
start -> end, // 차례로
end -> start, // 역순으로
----

==== 문자열
[source,js]
----
str,
'str'[start]: 's'
'str'[end]: 'r'
----

==== 배열
[source,js]
----
arr, // []
[item1, item2, ...item]: arr[index], 
arr[start]: item1, 
arr[end]: ...item, 
----

==== 객체
[source,js]
----
obj, // {}
{key1: value1, key2: value2, ...key: ...value}: obj.key,
src // key: value 
----

==== 함수
[source,js]
----
func,
p => p,
p, // 파라미터
p => p + 1, // 연산 함수 적용
p => p < 10, // 판별 함수 만족
(p1, p2, ...p) => return
----


==== 맵
[source,js]
----
map
----

==== 셋
[source,js]
----
set
----

==== 여러 형태가 가능한 대상
[source,js]
----
H,
(arr, obj, set, map ...)
----

== 용어와 개념

=== 얕게 복사

=== 반환 (return)

=== 확장

=== 동결 (freeze)

=== 밀봉 (sealed)

=== thisArg: 호출하는데 제공될 this 의 값

=== 열거 가능 (enumerable)

=== 유사 배열 (array-like)

=== 이터러블 (iterable)

=== 이터레이터 (iterator)

=== 원시값 (string, number, bigint (큰 정수), boolean, undefined, symbol)
객체가 아니면서 메소드도 가지지 않는 데이터 

=== 메소드: 대상에 할당된 함수
[source,js]
----
const user = {} // [], p => p ...
user.sayHi = () => console.log('Hi'); // user 객체에 sayHi() 함수 할당
user.sayHi(); // Hi
----

=== 메소드 체인
[source,js]
----
user.sayHi().sayBye().goToBed();
----
undefined 를 반환하는 메소드는 체인 중간에 올수 없음


 














